### ISSUE TITLE
Several shortcuts not working : zoom 0/+/- and F12 (including customed)

### ISSUE THREAD

**Issue by laurencechavet** [ThePacielloGroup/CCAe#328]
**Describe the bug**
“Ctrl 0”, “Ctrl +” and “Ctrl –“ for actual zoom and zoom in/out are not working.
F12 for the foreground picker is not working, even when you change it for another key in Preferences

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version CCA 3.4.2

**To Reproduce**
- Open the CCA in English, go in the main window "Color Contrast Analyser"
- Press Ctrl + + to zoom in,  nothing is happening, the shortcut key is not working
- Press Ctrl + - to zoom out, nothing is happening, the shortcut key is not working
- Go in the menu view, and Choose Zoom out, you see the window's size decrease. Press Ctrl +  0 to zoom back to the initial size, nothing is happening, the shortcut key is not working
- Press F11 to see the background picker. It opens. Cancel it. Press F12 to see the foreground picker. Nothing is happening, the shortcut key is not working
- Go in the menu "Color Contrast Analyser", choose "Preferences".  Change the picker foreground key to "F3" for example. Go back to the Color Contrast Analyser main window. Click F3, nothing is happening, the shortcut key is not working

**Expected behavior**
- Ctrl + + zoom in
- Ctrl + - zoom out
- Ctrl + 0 zoom to initial size
- F12 opens foreground picker
- You can customize the shortcut key of the foreground picker and it works

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ferllings** [comment]
I believe this has been fixed in v3.5.1

**Comment by laurencechavet** [comment]
Hi,

In v3.5.1, the following is still broken
- Ctrl + + zoom in
- Ctrl + - zoom out
- Ctrl + 0 zoom to initial size

In v3.5.1, the following has been fixed
- F12 opens foreground picker
- You can customize the shortcut key of the foreground picker and it works
- I tested also F11 and a custom key for background picker

Thanks

**Comment by ferllings** [comment]
Can't reproduce with latest build.
I've added numpad support
